import { type Metadata } from "next"
import { Geist } from "next/font/google"
import { ThemeProvider } from "~/components/theme/provider"
import "~/styles/globals.css"
import { TRPCReactProvider } from "~/trpc/react"

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  display: "swap",
  preload: true,
  weight: "400",
  fallback: ["system-ui", "sans-serif"],
})

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning className={geistSans.className}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TRPCReactProvider>{children}</TRPCReactProvider>{" "}
        </ThemeProvider>
      </body>
    </html>
  )
}
